workflows:
  default-workflow:
    name: Build APK
    max_build_duration: 30
    environment:
      flutter: stable
    scripts:
      - name: Build APK
        script: |
          flutter pub get
          flutter build apk --debug
    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk
    publishing:
      email:
        recipients:
          - your@email.com