name: ajo
description: A new Flutter project for Ajo app.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  # ✅ Firebase packages
  firebase_core: ^3.15.1
  firebase_auth: ^5.6.2
  cloud_firestore: ^5.6.11
  firebase_storage: 12.4.9  # ✅ for profile photo upload

  # ✅ Image picker for profile photo
  image_picker: ^1.1.1

  # ✅ Date formatting support
  intl: ^0.18.1

  # (Optional) For state management or UI improvements:
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/avatar.png  # ✅ Add default avatar image here